spring:
  application:
    name: event-processor
  autoconfigure:
    exclude:
      - com.google.cloud.spring.autoconfigure.pubsub.GcpPubSubAutoConfiguration
      - com.google.cloud.spring.autoconfigure.pubsub.GcpPubSubReactiveAutoConfiguration
      - com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration
  pulsar:
    client:
      service-url: pulsar://localhost:6650
    admin:
      service-url: http://localhost:8080
  cloud:
    function:
      definition: eventConsumer;processedEventConsumer
    stream:
      default-binder: pulsar
      bindings:
        eventProducer-out-0:
          destination: processed-events
          content-type: application/json
          binder: pulsar
        eventConsumer-in-0:
          destination: input-events
          content-type: application/json
          group: event-processor-group
          binder: pulsar
        processedEventConsumer-in-0:
          destination: processed-events
          content-type: application/json
          group: processed-consumer-group
          binder: pulsar

server:
  port: 7070

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,bindings
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.charter.elf: INFO
    org.springframework.cloud.stream: DEBUG
    org.springframework.pulsar: DEBUG
