spring:
  application:
    name: event-processor
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  cloud:
    function:
      definition: eventConsumer;processedEventConsumer
    stream:
      default-binder: rabbit
      bindings:
        eventProducer-out-0:
          destination: processed-events
          content-type: application/json
          binder: rabbit
        eventConsumer-in-0:
          destination: input-events
          content-type: application/json
          group: event-processor-group
          binder: rabbit
        processedEventConsumer-in-0:
          destination: processed-events
          content-type: application/json
          group: processed-consumer-group
          binder: rabbit
      rabbit:
        bindings:
          eventConsumer-in-0:
            consumer:
              autoBindDlq: true
              republishToDlq: true

server:
  port: 7070

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,bindings
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.charter.elf: INFO
    org.springframework.cloud.stream: DEBUG
